### Fetch Twilio Messages
GET https://api.twilio.com/2010-04-01/Accounts/[sid]/Messages.json
Authorization: Basic [token]

### Send WhatsApp Message
#POST https://d9miv23p28.execute-api.us-east-1.amazonaws.com/send-message
POST http://localhost:3000/send-message
Content-Type: application/json

{
  "to": "+5511966493808",
  "message": "Hello from Twilio WhatsApp API!"
}

### contact card
GET http://localhost:3000/gabe_contact.vcf
